In [17]:
import numpy as np
grid=[[3,8,0,0,6,9,0,4,0],
      [6,0,0,5,0,0,0,3,2],
      [0,9,0,3,0,0,1,0,0],
      [8,0,3,0,0,0,0,0,9],
      [9,4,0,0,8,0,0,5,7],
      [1,0,0,0,0,0,2,0,6],
      [0,0,8,0,0,6,0,9,0],
      [4,7,0,0,0,5,0,0,1],
      [0,6,0,9,4,0,0,7,3]]
#print(grid)
print(np.matrix(grid))

[[3 8 0 0 6 9 0 4 0]
 [6 0 0 5 0 0 0 3 2]
 [0 9 0 3 0 0 1 0 0]
 [8 0 3 0 0 0 0 0 9]
 [9 4 0 0 8 0 0 5 7]
 [1 0 0 0 0 0 2 0 6]
 [0 0 8 0 0 6 0 9 0]
 [4 7 0 0 0 5 0 0 1]
 [0 6 0 9 4 0 0 7 3]]


In [18]:
def suduko(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    x0=(x//3)*3
    y0=(y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == n:
                return False
    return True

In [19]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1,10):
                    if suduko(y,x,n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return    
    print(np.matrix(grid))

In [20]:
solve()

[[3 8 2 1 6 9 7 4 5]
 [6 1 4 5 7 8 9 3 2]
 [7 9 5 3 2 4 1 6 8]
 [8 2 3 6 5 7 4 1 9]
 [9 4 6 2 8 1 3 5 7]
 [1 5 7 4 9 3 2 8 6]
 [2 3 8 7 1 6 5 9 4]
 [4 7 9 8 3 5 6 2 1]
 [5 6 1 9 4 2 8 7 3]]
